services:

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn app.backend.v1.api:app --reload --workers 1 --host 0.0.0.0 --port 4000
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:4000
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.4-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 2s
      timeout: 5s
      retries: 15
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  app_data:
  db_data:
